name: fillink-test
description: An test adapter for fillink.
node_identifier: filink-1
platforms:
  - AWS Lambda
data_sources:
  - name: fillink-test
    url: https://filswan.com
parameters:
  - deal_id
  - network_name
